config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :cards do
    member do
      post 'check_translation', to: "cards#check_translation"
    end
  end

  resources :user_sessions
  resources :users

  resources :decks do
    member do
      patch 'make_current', to: "decks#make_current"
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/card.rb
class Card < ApplicationRecord
  REVIEWTIME_AND_BOX = {
    1 => 12.hours,
    2 => 3.days,
    3 => 1.week,
    4 => 2.weeks,
    5 => 1.month,
  }

  belongs_to :deck

  validates :original_text, :translated_text, :deck, presence: true
  validate :check_correct_word, on: [ :create, :update ]

  scope :ready_to_review, -> { where('review_date <= ?', Time.now).order(Arel.sql("RANDOM()"))  }
  scope :all_user_cards, -> (decks) {where(deck: decks) }

  before_save :set_review_date

  mount_uploader :photo, PhotoUploader

  def set_review_date
    self.review_date = Time.now if new_record?
  end

  def check_correct_word
    if self.original_text.blank? || self.translated_text.blank?
      return
    elsif self.original_text.downcase == self.translated_text.downcase
      errors.add(:card, "Перевод и оригинальный текст не могут быть равны!")
    end
  end

  def levenshtein(answer)
    DamerauLevenshtein.distance(translated_text.downcase, answer.downcase)
  end

  def correct_answer_logic
    if self.box <= 4
      update(box: self.box += 1, review_date: Time.now + REVIEWTIME_AND_BOX[self.box])
    else
      update(review_date: Time.now + 1.year)
    end
  end

  def wrong_answer_logic
    update(check_attempt: self.check_attempt += 1)
    if self.check_attempt == 4
      update(box: 1, check_attempt: 0, review_date: Time.now + REVIEWTIME_AND_BOX[self.box])
    end
    false
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
  has_many :cards

  validates :name, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, uniqueness: true

  has_many :authentications, :dependent => :destroy
  has_many :decks
  belongs_to :current_deck, class_name: 'Deck', optional: true

  scope :unverified_user_cards, -> { joins(decks: :cards).where('review_date <= ?', Time.now) }

  accepts_nested_attributes_for :authentications

  def author_of?(object)
    id == object.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def not_authenticated
    redirect_to login_url, :alert => "First login to access this page."
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy, :check_translation]

  def index
    @cards = Card.all_user_cards(current_user.decks)
  end

  def new
    @card = Card.new
  end

  def show
  end

  def edit
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to @card, :notice => "Карточка успешно создана!"
    else
      render 'new'
    end
  end

  def update
    if @card.update(card_params)
      redirect_to @card
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy if current_user.author_of?(@card.deck)
    redirect_to cards_path
  end

  def check_translation
    levenshtein = @card.levenshtein(params[:answer])
    if levenshtein == 0
      @card.correct_answer_logic
      flash[:notice] = "Правильно"
    elsif levenshtein.between?(1,2)
      @card.correct_answer_logic
      flash[:notice] = "Вы допустили опечатки, но Ваш ответ засчитан. Подробности ниже."
      flash[:user_answer] = "Ваш ответ: #{(params[:answer])}"
      flash[:correct_anser] = "Правильный ответ: #{@card.translated_text}"
    else
      @card.wrong_answer_logic
      flash[:notice] = "Не правильно"
    end
    redirect_to root_path
  end

private
  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :photo, :remote_photo_url, :deck_id)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :update, :edit, :make_current]

  def index
    @decks = current_user.decks.all
  end

  def new
    @deck = Deck.new
  end

  def show
  end

  def create
    @deck = Deck.new(deck_params.merge({ user: current_user }))

    if @deck.save
      redirect_to @deck, :notice => "Колода успешно создана!"
    else
      render 'new'
    end
  end

  def update
    if @deck.update(deck_params)
      redirect_to decks_path
    else
      render 'edit'
    end
  end

  def make_current
    current_user.update(current_deck_id: @deck.id) if current_user.author_of?(@deck)
    redirect_to decks_path
  end

private
  def set_deck
    @deck = Deck.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.present?
      @card = if current_user.current_deck.present?
        current_user.current_deck.cards.ready_to_review.last
      else
        Card.all_user_cards(current_user.decks).ready_to_review.last
      end
    end
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_action :require_login, raise: false

  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, :alert => "Failed to login from #{provider.titleize}!"
      end
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to(@user, notice: 'Вход выполнен успешно!')
    else
      flash.now[:alert] = 'Неуспешно!'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Выход выполнен!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy, :edit, :update]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_url, :notice => "Вы зарегистрировались"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, :notice => "Данные успешно обновлены!"
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, :notice => "Аккаунт удален"
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<% if current_user.decks.empty? %>
  <h3> Нельзя создать карточку если у Вас нет не одной колоды. Создаейте хотя бы одну колоду</h3>
<% else %>
  <%= simple_form_for( @card, html: { class: 'form-group' }) do |f| %>
     <%= f.input :original_text, placeholder: "Введите слово" %>
     <%= f.input :translated_text, placeholder: "Перевод слова" %>
     <% if @card.id %>
       <%= f.input :review_date, placeholder: "Дата пересмотра" %>
     <% end %>
     <%= f.collection_select(:deck_id, current_user.decks, :id, :name) %>
     <%= f.input :photo, as: :file  %>
     <%= f.input :remote_photo_url , placeholder: "Введите URL фотографии" %>
     <%= f.submit button_name, class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/cards/edit.html.erb
<h1>Редактирование карточки</h1>
<%= render 'form', button_name: "Сохранить" %>

app/views/cards/index.html.erb
<table class="table table-bordered text-center">
  <thead>
    <tr>
      <th scope="col">Оригинальный текст</th>
      <th scope="col">Перевод</th>
      <th scope="col">Дата пересмотра</th>
    </tr>
  </thead>
    <tbody>
      <% @cards.each do |card| %>
          <td><%= card.original_text %></td>
          <td><%= card.translated_text %></td>
          <td><%= card.review_date.strftime('%m/%d/%y') %></td>
          <% if current_user.author_of?(card.deck) %>
            <td><%= link_to 'Edit', edit_card_path(card) %></td>
            <td><%= link_to 'Destroy', card_path(card),method: :delete, data: { confirm: 'Вы уверены?' } %></td>
          <% end %>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/cards/new.html.erb
<%= render 'form', button_name: "Создать" %>
<%= link_to "Создать колоду", new_deck_path %>

app/views/cards/show.html.erb
<div class="text-center">
  <h1><%= @card.original_text %></h1>
  <h1><%= @card.translated_text %></h1>
  <h1><%= @card.review_date %></h1>
  <% if @card.photo.present? %>
    <h1><%= image_tag @card.photo.url %></h1>
  <% else %>
    <h1><%= image_tag @card.remote_photo_url if @card.remote_photo_url.present? %></h1>
    <% end %>
  <% if current_user.author_of?(@card.deck)%>
    <%= link_to 'Удалить карточку', card_path(@card),method: :delete, data: { confirm: 'Вы уверены?' } %>
  <% end %>
</div>

app/views/decks/_form.html.erb
<%= simple_form_for( @deck, html: { class: 'form-group' }) do |f| %>
   <%= f.input :name, placeholder: "Название колоды" %>
   <%= f.submit button_name, class: "btn btn-primary" %>
<% end %>

app/views/decks/edit.html.erb
<h1>Редактирование колоды</h1>
<%= render 'form', button_name: "Сохранить" %>

app/views/decks/index.html.erb
<table class="table table-bordered text-center">
  <thead>
    <tr>
      <th scope="col">Название колоды</th>
      <th scope="col">Статус</th>
    </tr>
  </thead>
    <tbody>
      <% current_user.decks.each do |deck| %>
          <td><%= deck.name %></td>
          <% if current_user.author_of?(deck) %>
            <td><%= link_to 'Редактировать', edit_deck_path(deck) %></td>
            <td><%= link_to 'Сделать текущей', make_current_deck_path(deck), method: :patch %></td>
          <% end %>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/decks/new.html.erb
<h1>Новая колода</h1>
<%= render 'form', button_name: "Создать" %>

app/views/decks/show.html.erb
<h1><%= @deck.name %></h1>
<% if current_user.author_of?(@deck) %>
  <%= link_to 'Редактировать', edit_deck_path(@deck) %>
<% end %>

app/views/home/index.html.erb
<% if current_user %>
  <% if @card.present? %>
    <%= form_tag check_translation_card_path(@card) do %>
    <div class="text-center">
      <h2><%= image_tag @card.photo.url if @card.photo.present? %></h2>
      <h2><%= @card.original_text %></h2>
    </div>
        <div class="row">
          <div class="input-group">
            <%= text_field_tag "answer", nil, class: "form-control", placeholder: "Ответ"  %>
              <span class="input-group-btn">
                  <%= submit_tag "Проверить", class: "btn btn-success" %>
              </span>
          </div>
        </div>
    <% end %>
    <% else%>
      <h1> На данный момент все карточки проверены!</h1>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcards</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id="container">

      <div class="navbar navbar-default navbar-static-top">
        <%= link_to "Флэшкарточек", root_path, class: 'navbar-brand' %>
        <nav class="nav">
            <% if current_user %>
              <a class="nav-link"> <%= link_to "Мои карточки", cards_path %></a>
              <a class="nav-link"> <%= link_to "Добавить карточку", new_card_path %></a>
              <a class="nav-link"> <%= link_to "Мои колоды", decks_path %></a>
              <a class="nav-link"> <%= link_to "Создать колоду", new_deck_path %></a>
              <a class="nav-link"> <%= link_to "Профиль", edit_user_path(current_user.id) %></a>
              <a class="nav-link"> <%= link_to "Выход", :logout, method: :post %></a>
            <% else %>
              <a class="nav-link"> <%= link_to "Регистрация", new_user_path %></a>
              <a class="nav-link"> <%= link_to "Вход", :login %></a>
              <a class="nav-link"> <%= link_to 'Login GitHub', auth_at_provider_path(provider: :github) %></a>
            <% end %>
        </nav>
      </nav>
    </section>

      <section id="container">
        <% flash.each do |name, msg| %>
          <div class="text-center">
          <h3><%= content_tag :div, msg, :id => "flash_#{name}" %></h3>
          </div>
        <% end %>
        <%= yield %>
      </section>
  </body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Войти" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Меню входа</h1>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= simple_form_for @user, html: { class: "form-horizontal" } do |f| %>
  <%= f.input :email, placeholder: "Email" %>
  <%= f.input :password, placeholder: "Пароль" %>
  <%= f.input :password_confirmation, placeholder: "Повторите пароль" %>
  <%= f.submit button_name, class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', button_name: "Сохранить" %>

app/views/users/new.html.erb
<%= render 'form', button_name: "Создать" %>

app/views/users/show.html.erb
<h3>Вы находитесь в Вашем личном кабинете</h3>
<p> Ваш Email: <%= @user.email %></p>
<%= link_to "Удалить", user_path(@user), method: :delete, data: {confirm: "Вы уверены?"}, class: "btn btn-danger" %>